### PR TITLE
use java 16 for ci

### PR DESCRIPTION
**Pull request by danielphan2003**

### CODE REVIEW

**Comment by Tfarcenim** [comment]
Why do people care about ci so much, what does it do?

**Comment by darkfang1989** [comment]
if it's what i'm thinking, it's the "clear inventory" command? what i read googling "ci"

**Comment by danielphan2003** [comment]
I just want to get the latest release without going through CurseForge.

**Comment by darkfang1989** [comment]
but what is ci?

**Comment by Tfarcenim** [comment]
> I just want to get the latest release without going through CurseForge.

That will almost always get you a broken mod and no support, there's a reason I don't publish every commit to curseforge.

**Comment by danielphan2003** [comment]
Yes, I know I should not use CI versions, but can you at lease tag release versions on GitHub? Automation tools can't use CurseForge to fetch the latest jar file, and having release artifacts on GitHub makes it much easier to manage.

**Comment by danielphan2003** [comment]
I will make a GitHub action that push release artifacts every time you tag a release. That way, users won't have to go to CurgeForge for downloads, and it would be easier for them to report issues here, too.

**Comment by danielphan2003** [comment]
> but what is ci?
> 

Continuous Integration. It basically means an action is executed every time a commit appears. That way, developers can test each commits and tag release version without the hassle of uploading artifacts manually.

**Comment by Tfarcenim** [comment]
Oh, I don't tag releases very often because of the erratic nature of MC mods. Anyways, I'll merge this now.

**Pull request merged**
