### PR TITLE
Some Changes

### LINKED ISSUE #3: Fabric API Dependency Unnecessary?
I was curious how this mod utilizes the Fabric API considering its dependency on it, but after reviewing the code I can't find any use of the Fabric API. All of the imports are from Mixin, Minecraft, or the mods own packages. The dependency seems to be a relic from the fabric example mod including the suggested "flamingo" mod.

Am I missing something, or can this dependency be removed? Right now this mod is the only reason I load the fabric API on my server at all!

### LINKED ISSUE #4: Update License and README on GitHub
The license information on GitHub says CC0.  Your CurseForge claims that this is a port of Shadows-of-Fire/FastFurnace; if thatʼs true then you donʼt own the copyright to a lot of the code and you therefore canʼt give that up.  CurseForge says you used the MIT license, which you can legally use; you should update the GitHub page to include that and to clarify which parts were written by Shadows-of-Fire and which were written by you.

Additionally, it would be nice if the README was about the actual mod and not the example project you used to make this from.

### LINKED ISSUE #6: Requires update for Mod Menu
Mod menu changed recently and the icon here is now broken
`[main/WARN]: Warning! Mod fastfurnace has a broken icon, loading default icon`

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
- Added GitHub Actions to build on push and pull request (Ubuntu, JDK 11)
- Changed actual license file to MIT (properly fixes #4)
- Changes README to be about this mod itself (properly fixes #4)
- Bump loom version to 0.6 (to build on JDK 16)
- Remove deprecated `modCompile` (to build on JDK 16)
- Bump gradle version to 6.8.3
- Add mod icon (fixes #6)
- Adds links to `fabric.mod.json`
- Add fabric API dependency (properly closes #3)
- Add fueltimecache incompatibility (this does everything that mod does, and more)
- Remove useless 'client' part from `mixins.json` file

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
Have confirmed that:

- This mod builds
- The game launches
- The mod works

**Comment by Tfarcenim** [comment]
Why was the fabric api dependency readded, the whole point of removing it was so people could use the mod without fabric api.

**Comment by DragonEggBedrockBreaking** [comment]
> Why was the fabric api dependency readded, the whole point of removing it was so people could use the mod without fabric api.

Oh, sorry, I have misunderstood what you said in the previous issue.

**Comment by DragonEggBedrockBreaking** [comment]
You should make 1.16.x the main branch, so that the license works, and so it is more clear which part of the repo is correct.

**Pull request merged**
